### PR TITLE
Fixed travis dependencies

### PR DESCRIPTION
**Pull request by prokopsimek**

### CODE REVIEW

**Comment by prokopsimek** [comment]
@sshaw What do think about it? Is it ok? All travis tests passed.

**Comment by sshaw** [comment]
Looks good, but you should keep your Coveralls token a secret. From [the docs](https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails):

> The option repo_token (found on your repository's page on Coveralls) is used to specify which project on Coveralls your project maps to. This is only needed for repos not using a CI and should be kept secret -- anyone could use it to submit coverage data on your repo's behalf.

**Comment by prokopsimek** [comment]
@sshaw I have set this repo_token as Travis ENV variable, but it does not work. Don't know what I'm doing wrong.

**Comment by sshaw** [comment]
Sorry @prokopsimek, I've never used coveralls or env vars via TravisCI

**Pull request merged**
